name: bluelink_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  # Fixed: Moved outside the flutter: sdk block
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#E6F2FF"

  image: assets/images/logo.png

  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  fullscreen: true

  android_12:
    image: assets/images/logo.png
    color: "#E6F2FF"
    icon_background_color: "#E6F2FF"